name: Update Homebrew tap

on:
  release:
    types: [published]

jobs:
  update-homebrew-tap:
    name: Update Homebrew tap
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Update Homebrew tap
        uses: dayflower/brew-up@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release-tag: ${{ github.ref_name }}
          template-path: homebrew/popmark.rb.tmpl
          output-path: Casks/popmark.rb
          asset-map: |
            default=popmark-{{version}}-macos.zip
          target-repo: dayflower/homebrew-tap
          target-branch: main
          target-repo-token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          publish-mode: pr
